"""Pydantic schema for invoice extraction.

Drives both vLLM `guided_json` and OpenAI / Gemini structured-output features.

Design notes:
- Every field is required (no defaults). "Optional" means `T | None` — the
  model emits explicit null instead of omitting the key. This satisfies
  OpenAI strict mode and gives downstream code a uniform output shape.
- `extra="forbid"` so the model can't invent new keys.
- JSON Schema is generated by Pydantic; we don't hand-write it. The
  `INVOICE_JSON_SCHEMA` constant is what gets fed to vLLM / OpenAI.
"""

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class LineItem(BaseModel):
    """One line on an invoice — a single product or service entry."""

    model_config = ConfigDict(extra="forbid")

    description: str = Field(description="Item or service description, as printed")
    quantity: float = Field(description="Quantity (use 1 if no quantity column is shown)")
    unit_price: float = Field(description="Per-unit price before discounts")
    amount: float = Field(description="Line total (typically quantity * unit_price), as printed")


class Invoice(BaseModel):
    """Structured invoice extracted from OCR'd receipt text."""

    model_config = ConfigDict(extra="forbid")

    vendor_name: str | None = Field(
        description="Merchant / vendor name as printed at the top of the receipt. Null if not present."
    )
    invoice_number: str | None = Field(
        description="Invoice, receipt, or order number. Null if no such field is on the document."
    )
    invoice_date: str | None = Field(
        description="Date in ISO YYYY-MM-DD. Null if no date is shown."
    )
    total_amount: float | None = Field(
        description="Final amount due AFTER taxes and discounts. Null if not present."
    )
    currency: str | None = Field(
        description="ISO 4217 code (USD, MYR, EUR, GBP, ...). Null if currency cannot be determined."
    )
    line_items: list[LineItem] = Field(
        description="Itemized lines. Empty list if the receipt has no visible line items."
    )


INVOICE_JSON_SCHEMA: dict[str, Any] = Invoice.model_json_schema()
"""JSON Schema for the Invoice model. Feed to vLLM `guided_json` or OpenAI
`response_format`. Generated once at import — treat as immutable."""
